<?php
// Register Custom Post Type
function careunit_post_type() {

	$labels = array(
		'name'                  => _x( 'Clinical Services', 'Post Type General Name', 'careunit' ),
		'singular_name'         => _x( 'Clinical Service', 'Post Type Singular Name', 'careunit' ),
		'menu_name'             => __( 'Clinical Service', 'careunit' ),
		'name_admin_bar'        => __( 'Clinical Service', 'careunit' ),
		'archives'              => __( 'Item Archives', 'careunit' ),
		'attributes'            => __( 'Item Attributes', 'careunit' ),
		'parent_item_colon'     => __( 'Parent Item:', 'careunit' ),
		'all_items'             => __( 'All Items', 'careunit' ),
		'add_new_item'          => __( 'Add New Item', 'careunit' ),
		'add_new'               => __( 'Clinical Service', 'careunit' ),
		'new_item'              => __( 'Clinical Service', 'careunit' ),
		'edit_item'             => __( 'Edit Item', 'careunit' ),
		'update_item'           => __( 'Update Item', 'careunit' ),
		'view_item'             => __( 'View Item', 'careunit' ),
		'view_items'            => __( 'View Items', 'careunit' ),
		'search_items'          => __( 'Search Item', 'careunit' ),
		'not_found'             => __( 'Not found', 'careunit' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'careunit' ),
		'featured_image'        => __( 'Featured Image', 'careunit' ),
		'set_featured_image'    => __( 'Set featured image', 'careunit' ),
		'remove_featured_image' => __( 'Remove featured image', 'careunit' ),
		'use_featured_image'    => __( 'Use as featured image', 'careunit' ),
		'insert_into_item'      => __( 'Insert into item', 'careunit' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'careunit' ),
		'items_list'            => __( 'Items list', 'careunit' ),
		'items_list_navigation' => __( 'Items list navigation', 'careunit' ),
		'filter_items_list'     => __( 'Filter items list', 'careunit' ),
	);
	$args = array(
		'label'                 => __( 'Clinical Service', 'careunit' ),
		'description'           => __( 'Clinical Service', 'careunit' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'excerpt', 'thumbnail', ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'clinical_service', $args );
    
    $careunit_service_labels = array(
		'name'                  => _x( 'Services', 'Post Type General Name', 'careunit' ),
		'singular_name'         => _x( 'Service', 'Post Type Singular Name', 'careunit' ),
		'menu_name'             => esc_html__( 'Services', 'careunit' ),
		'name_admin_bar'        => esc_html__( 'Services', 'careunit' ),
		'archives'              => esc_html__( 'Services Archives', 'careunit' ),
		'attributes'            => esc_html__( 'Services Attributes', 'careunit' ),
		'parent_item_colon'     => esc_html__( 'Parent Item:', 'careunit' ),
		'all_items'             => esc_html__( 'All Services', 'careunit' ),
		'add_new_item'          => esc_html__( 'Add New Service', 'careunit' ),
		'add_new'               => esc_html__( 'Add New Service', 'careunit' ),
		'new_item'              => esc_html__( 'New Service', 'careunit' ),
		'edit_item'             => esc_html__( 'Services Edit', 'careunit' ),
		'update_item'           => esc_html__( 'Update Services', 'careunit' ),
		'view_item'             => esc_html__( 'View Item', 'careunit' ),
		'view_items'            => esc_html__( 'View Services item', 'careunit' ),
		'search_items'          => esc_html__( 'Services Search', 'careunit' ),
		'not_found'             => esc_html__( 'Not found', 'careunit' ),
		'not_found_in_trash'    => esc_html__( 'Not found in Trash', 'careunit' ),
		'featured_image'        => esc_html__( 'Featured Image', 'careunit' ),
		'set_featured_image'    => esc_html__( 'Set featured image', 'careunit' ),
		'remove_featured_image' => esc_html__( 'Remove featured image', 'careunit' ),
		'use_featured_image'    => esc_html__( 'Use as featured image', 'careunit' ),
		'insert_into_item'      => esc_html__( 'Insert into item', 'careunit' ),
		'uploaded_to_this_item' => esc_html__( 'Uploaded to Services item', 'careunit' ),
		'items_list'            => esc_html__( 'Services item list', 'careunit' ),
		'items_list_navigation' => esc_html__( 'Services list navigation', 'careunit' ),
		'filter_items_list'     => esc_html__( 'Filter items list', 'careunit' ),
	);
	$service_args = array(
		'label'                 => esc_html__( 'Service', 'careunit' ),
		'description'           => esc_html__( 'careunit Service', 'careunit' ),
		'labels'                => $careunit_service_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions', ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-migrate'
	);
	register_post_type( 'careunit_service', $service_args );
    $labels = array(
		'name'                  => _x( 'Doctor Tabs', 'Post Type General Name', 'careunit' ),
		'singular_name'         => _x( 'Doctor Tab', 'Post Type Singular Name', 'careunit' ),
		'menu_name'             => __( 'Doctor Tab', 'careunit' ),
		'name_admin_bar'        => __( 'Doctor Tab', 'careunit' ),
		'archives'              => __( 'Item Archives', 'careunit' ),
		'attributes'            => __( 'Item Attributes', 'careunit' ),
		'parent_item_colon'     => __( 'Parent Item:', 'careunit' ),
		'all_items'             => __( 'All Items', 'careunit' ),
		'add_new_item'          => __( 'Add New Item', 'careunit' ),
		'add_new'               => __( 'Doctor Tab', 'careunit' ),
		'new_item'              => __( 'Doctor Tab', 'careunit' ),
		'edit_item'             => __( 'Edit Item', 'careunit' ),
		'update_item'           => __( 'Update Item', 'careunit' ),
		'view_item'             => __( 'View Item', 'careunit' ),
		'view_items'            => __( 'View Items', 'careunit' ),
		'search_items'          => __( 'Search Item', 'careunit' ),
		'not_found'             => __( 'Not found', 'careunit' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'careunit' ),
		'featured_image'        => __( 'Featured Image', 'careunit' ),
		'set_featured_image'    => __( 'Set featured image', 'careunit' ),
		'remove_featured_image' => __( 'Remove featured image', 'careunit' ),
		'use_featured_image'    => __( 'Use as featured image', 'careunit' ),
		'insert_into_item'      => __( 'Insert into item', 'careunit' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'careunit' ),
		'items_list'            => __( 'Items list', 'careunit' ),
		'items_list_navigation' => __( 'Items list navigation', 'careunit' ),
		'filter_items_list'     => __( 'Filter items list', 'careunit' ),
	);
	$args = array(
		'label'                 => __( 'Doctor Tab', 'careunit' ),
		'description'           => __( 'Doctor Details Description', 'careunit' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'excerpt', 'thumbnail', ),
		'taxonomies'            => array( 'doctab_cat' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'doctor_tab', $args );
    $labels = array(
		'name'                  => _x( 'Patients Sayings', 'Post Type General Name', 'careunit' ),
		'singular_name'         => _x( 'Patients Saying', 'Post Type Singular Name', 'careunit' ),
		'menu_name'             => __( 'Patients Saying', 'careunit' ),
		'name_admin_bar'        => __( 'Patients Saying', 'careunit' ),
		'archives'              => __( 'Item Archives', 'careunit' ),
		'attributes'            => __( 'Item Attributes', 'careunit' ),
		'parent_item_colon'     => __( 'Parent Item:', 'careunit' ),
		'all_items'             => __( 'All Items', 'careunit' ),
		'add_new_item'          => __( 'Add New Item', 'careunit' ),
		'add_new'               => __( 'Patients Saying', 'careunit' ),
		'new_item'              => __( 'Patients Saying', 'careunit' ),
		'edit_item'             => __( 'Edit Item', 'careunit' ),
		'update_item'           => __( 'Update Item', 'careunit' ),
		'view_item'             => __( 'View Item', 'careunit' ),
		'view_items'            => __( 'View Items', 'careunit' ),
		'search_items'          => __( 'Search Item', 'careunit' ),
		'not_found'             => __( 'Not found', 'careunit' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'careunit' ),
		'featured_image'        => __( 'Featured Image', 'careunit' ),
		'set_featured_image'    => __( 'Set featured image', 'careunit' ),
		'remove_featured_image' => __( 'Remove featured image', 'careunit' ),
		'use_featured_image'    => __( 'Use as featured image', 'careunit' ),
		'insert_into_item'      => __( 'Insert into item', 'careunit' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'careunit' ),
		'items_list'            => __( 'Items list', 'careunit' ),
		'items_list_navigation' => __( 'Items list navigation', 'careunit' ),
		'filter_items_list'     => __( 'Filter items list', 'careunit' ),
	);
	$args = array(
		'label'                 => __( 'Patients Saying', 'careunit' ),
		'description'           => __( 'Patients Saying Text', 'careunit' ),
		'labels'                => $labels,
		'supports'              => array( 'editor', 'excerpt', 'thumbnail','title' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'patients_saying', $args );
    $labels = array(
		'name'                  => _x( 'Our History', 'Post Type General Name', 'careunit' ),
		'singular_name'         => _x( 'Our History', 'Post Type Singular Name', 'careunit' ),
		'menu_name'             => __( 'Our History', 'careunit' ),
		'name_admin_bar'        => __( 'Our History', 'careunit' ),
		'archives'              => __( 'Item Archives', 'careunit' ),
		'attributes'            => __( 'Item Attributes', 'careunit' ),
		'parent_item_colon'     => __( 'Parent Item:', 'careunit' ),
		'all_items'             => __( 'All Items', 'careunit' ),
		'add_new_item'          => __( 'Add New Item', 'careunit' ),
		'add_new'               => __( 'Our History', 'careunit' ),
		'new_item'              => __( 'Our History', 'careunit' ),
		'edit_item'             => __( 'Edit Item', 'careunit' ),
		'update_item'           => __( 'Update Item', 'careunit' ),
		'view_item'             => __( 'View Item', 'careunit' ),
		'view_items'            => __( 'View Items', 'careunit' ),
		'search_items'          => __( 'Search Item', 'careunit' ),
		'not_found'             => __( 'Not found', 'careunit' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'careunit' ),
		'featured_image'        => __( 'Featured Image', 'careunit' ),
		'set_featured_image'    => __( 'Set featured image', 'careunit' ),
		'remove_featured_image' => __( 'Remove featured image', 'careunit' ),
		'use_featured_image'    => __( 'Use as featured image', 'careunit' ),
		'insert_into_item'      => __( 'Insert into item', 'careunit' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'careunit' ),
		'items_list'            => __( 'Items list', 'careunit' ),
		'items_list_navigation' => __( 'Items list navigation', 'careunit' ),
		'filter_items_list'     => __( 'Filter items list', 'careunit' ),
	);
	$args = array(
		'label'                 => __( 'Our History', 'careunit' ),
		'description'           => __( 'Our History Text', 'careunit' ),
		'labels'                => $labels,
		'supports'              => array( 'editor', 'excerpt', 'thumbnail','title' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'our_history', $args );

}
add_action( 'init', 'careunit_post_type', 0 );


// Register Custom Taxonomy
function careunit_custom_taxonomy() {

	$labels = array(
		'name'                       => _x( 'Doctor Tab Categories', 'Taxonomy General Name', 'careunit' ),
		'singular_name'              => _x( 'Doctor Tab Categorie', 'Taxonomy Singular Name', 'careunit' ),
		'menu_name'                  => __( 'Doctor Tab Categorie', 'careunit' ),
		'all_items'                  => __( 'Doctor Tab Categorie', 'careunit' ),
		'parent_item'                => __( 'Parent Item', 'careunit' ),
		'parent_item_colon'          => __( 'Parent Item:', 'careunit' ),
		'new_item_name'              => __( 'Doctor Tab Categorie', 'careunit' ),
		'add_new_item'               => __( 'Doctor Tab Categorie', 'careunit' ),
		'edit_item'                  => __( 'Edit Item', 'careunit' ),
		'update_item'                => __( 'Update Item', 'careunit' ),
		'view_item'                  => __( 'View Item', 'careunit' ),
		'separate_items_with_commas' => __( 'Separate items with commas', 'careunit' ),
		'add_or_remove_items'        => __( 'Add or remove items', 'careunit' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'careunit' ),
		'popular_items'              => __( 'Popular Items', 'careunit' ),
		'search_items'               => __( 'Search Items', 'careunit' ),
		'not_found'                  => __( 'Not Found', 'careunit' ),
		'no_terms'                   => __( 'No items', 'careunit' ),
		'items_list'                 => __( 'Items list', 'careunit' ),
		'items_list_navigation'      => __( 'Items list navigation', 'careunit' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => false,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'doctor_category', array( 'doctor_tab' ), $args );

}
add_action( 'init', 'careunit_custom_taxonomy', 0 );