<?php
// Register Custom Post Type
function dexpress_post_type() {
    $dexpress_service_labels = array(
		'name'                  => _x( 'Services', 'Post Type General Name', 'dexpress' ),
		'singular_name'         => _x( 'Service', 'Post Type Singular Name', 'dexpress' ),
		'menu_name'             => esc_html__( 'Services', 'dexpress' ),
		'name_admin_bar'        => esc_html__( 'Services', 'dexpress' ),
		'archives'              => esc_html__( 'Services Archives', 'dexpress' ),
		'attributes'            => esc_html__( 'Services Attributes', 'dexpress' ),
		'parent_item_colon'     => esc_html__( 'Parent Item:', 'dexpress' ),
		'all_items'             => esc_html__( 'All Services', 'dexpress' ),
		'add_new_item'          => esc_html__( 'Add New Service', 'dexpress' ),
		'add_new'               => esc_html__( 'Add New Service', 'dexpress' ),
		'new_item'              => esc_html__( 'New Service', 'dexpress' ),
		'edit_item'             => esc_html__( 'Services Edit', 'dexpress' ),
		'update_item'           => esc_html__( 'Update Services', 'dexpress' ),
		'view_item'             => esc_html__( 'View Item', 'dexpress' ),
		'view_items'            => esc_html__( 'View Services item', 'dexpress' ),
		'search_items'          => esc_html__( 'Services Search', 'dexpress' ),
		'not_found'             => esc_html__( 'Not found', 'dexpress' ),
		'not_found_in_trash'    => esc_html__( 'Not found in Trash', 'dexpress' ),
		'featured_image'        => esc_html__( 'Featured Image', 'dexpress' ),
		'set_featured_image'    => esc_html__( 'Set featured image', 'dexpress' ),
		'remove_featured_image' => esc_html__( 'Remove featured image', 'dexpress' ),
		'use_featured_image'    => esc_html__( 'Use as featured image', 'dexpress' ),
		'insert_into_item'      => esc_html__( 'Insert into item', 'dexpress' ),
		'uploaded_to_this_item' => esc_html__( 'Uploaded to Services item', 'dexpress' ),
		'items_list'            => esc_html__( 'Services item list', 'dexpress' ),
		'items_list_navigation' => esc_html__( 'Services list navigation', 'dexpress' ),
		'filter_items_list'     => esc_html__( 'Filter items list', 'dexpress' ),
	);
	$service_args = array(
		'label'                 => esc_html__( 'Service', 'dexpress' ),
		'description'           => esc_html__( 'dexpress Service', 'dexpress' ),
		'labels'                => $dexpress_service_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions','excerpt','page-attributes' ),
		//'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-migrate'
	);
	register_post_type( 'dexpress-service', $service_args );
    
	$dexpress_work_labels = array(
		'name'                  => _x( 'Work', 'Post Type General Name', 'dexpress' ),
		'singular_name'         => _x( 'Work', 'Post Type Singular Name', 'dexpress' ),
		'menu_name'             => esc_html__( 'Work', 'dexpress' ),
		'name_admin_bar'        => esc_html__( 'Work', 'dexpress' ),
		'archives'              => esc_html__( 'Work Archives', 'dexpress' ),
		'attributes'            => esc_html__( 'Work Attributes', 'dexpress' ),
		'parent_item_colon'     => esc_html__( 'Parent Item:', 'dexpress' ),
		'all_items'             => esc_html__( 'All Work', 'dexpress' ),
		'add_new_item'          => esc_html__( 'Add New Work', 'dexpress' ),
		'add_new'               => esc_html__( 'Add New Work', 'dexpress' ),
		'new_item'              => esc_html__( 'New Work', 'dexpress' ),
		'edit_item'             => esc_html__( 'Work Edit', 'dexpress' ),
		'update_item'           => esc_html__( 'Update Work', 'dexpress' ),
		'view_item'             => esc_html__( 'View Item', 'dexpress' ),
		'view_items'            => esc_html__( 'View Work item', 'dexpress' ),
		'search_items'          => esc_html__( 'Work Search', 'dexpress' ),
		'not_found'             => esc_html__( 'Not found', 'dexpress' ),
		'not_found_in_trash'    => esc_html__( 'Not found in Trash', 'dexpress' ),
		'featured_image'        => esc_html__( 'Featured Image', 'dexpress' ),
		'set_featured_image'    => esc_html__( 'Set featured image', 'dexpress' ),
		'remove_featured_image' => esc_html__( 'Remove featured image', 'dexpress' ),
		'use_featured_image'    => esc_html__( 'Use as featured image', 'dexpress' ),
		'insert_into_item'      => esc_html__( 'Insert into item', 'dexpress' ),
		'uploaded_to_this_item' => esc_html__( 'Uploaded to Work item', 'dexpress' ),
		'items_list'            => esc_html__( 'Work item list', 'dexpress' ),
		'items_list_navigation' => esc_html__( 'Work list navigation', 'dexpress' ),
		'filter_items_list'     => esc_html__( 'Filter items list', 'dexpress' ),
	);
	$work_args = array(
		'label'                 => esc_html__( 'Work', 'dexpress' ),
		'description'           => esc_html__( 'dexpress Work', 'dexpress' ),
		'labels'                => $dexpress_work_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions','view_mode_post_types','video','page-attributes' ),
		//'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-migrate'
	);
	register_post_type( 'dexpress-work', $work_args );
    
    //  testimonial post type
		$testimonial_labels = array(
			'name'                => _x( 'Testimonials', 'Post Type General Name', 'dexpress' ),
			'singular_name'       => _x( 'Testimonial', 'Post Type Singular Name', 'dexpress' ),
			'menu_name'           => esc_html__( 'Testimonials', 'dexpress' ),
			'name_admin_bar'      => esc_html__( 'Testimonials', 'dexpress' ),
			'parent_item_colon'   => esc_html__( 'Parent Testimonial:', 'dexpress' ),
			'all_items'           => esc_html__( 'All Testimonials', 'dexpress' ),
			'add_new_item'        => esc_html__( 'Add Testimonials', 'dexpress' ),
			'add_new'             => esc_html__( 'Add Testimonial', 'dexpress' ),
			'new_item'            => esc_html__( 'New Testimonial', 'dexpress' ),
			'edit_item'           => esc_html__( 'Edit Testimonial', 'dexpress' ),
			'update_item'         => esc_html__( 'Update Testimonial', 'dexpress' ),
			'view_item'           => esc_html__( 'View Testimonial', 'dexpress' ),
			'search_items'        => esc_html__( 'Search Testimonial', 'dexpress' ),
			'not_found'           => esc_html__( 'Not found', 'dexpress' ),
			'not_found_in_trash'  => esc_html__( 'Not found in Trash', 'dexpress' ),
		);
		
		$testimonial_args = array(
			'label'               => esc_html__( 'Testimonial', 'dexpress' ),
			'description'         => esc_html__( 'Testimonial', 'dexpress' ),
			'labels'              => $testimonial_labels,
			'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions', 'page-attributes', ),
			'hierarchical'        => false,
			'public'              => true,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'menu_position'       => 20,
			'menu_icon'           => 'dashicons-format-chat',
			'show_in_admin_bar'   => true,
			'show_in_nav_menus'   => true,
			'can_export'          => true,
			'has_archive'         => true,		
			'exclude_from_search' => false,
			'publicly_queryable'  => true,
			'capability_type'     => 'post',
		);
		register_post_type( 'dexpress_testimonial', $testimonial_args );
        $dexpress_team_labels = array(
            'name'                  => _x( 'Teams', 'Post Type General Name', 'dexpress' ),
            'singular_name'         => _x( 'Team', 'Post Type Singular Name', 'dexpress' ),
            'menu_name'             => esc_html__( 'Teams', 'dexpress' ),
            'name_admin_bar'        => esc_html__( 'Teams', 'dexpress' ),
            'archives'              => esc_html__( 'Teams Archives', 'dexpress' ),
            'attributes'            => esc_html__( 'Teams Attributes', 'dexpress' ),
            'parent_item_colon'     => esc_html__( 'Parent Item:', 'dexpress' ),
            'all_items'             => esc_html__( 'All Teams', 'dexpress' ),
            'add_new_item'          => esc_html__( 'Add New Team', 'dexpress' ),
            'add_new'               => esc_html__( 'Add New Team', 'dexpress' ),
            'new_item'              => esc_html__( 'New Team', 'dexpress' ),
            'edit_item'             => esc_html__( 'Teams Edit', 'dexpress' ),
            'update_item'           => esc_html__( 'Update Teams', 'dexpress' ),
            'view_item'             => esc_html__( 'View Item', 'dexpress' ),
            'view_items'            => esc_html__( 'View Teams item', 'dexpress' ),
            'search_items'          => esc_html__( 'Teams Search', 'dexpress' ),
            'not_found'             => esc_html__( 'Not found', 'dexpress' ),
            'not_found_in_trash'    => esc_html__( 'Not found in Trash', 'dexpress' ),
            'featured_image'        => esc_html__( 'Featured Image', 'dexpress' ),
            'set_featured_image'    => esc_html__( 'Set featured image', 'dexpress' ),
            'remove_featured_image' => esc_html__( 'Remove featured image', 'dexpress' ),
            'use_featured_image'    => esc_html__( 'Use as featured image', 'dexpress' ),
            'insert_into_item'      => esc_html__( 'Insert into item', 'dexpress' ),
            'uploaded_to_this_item' => esc_html__( 'Uploaded to Teams item', 'dexpress' ),
            'items_list'            => esc_html__( 'Teams item list', 'dexpress' ),
            'items_list_navigation' => esc_html__( 'Teams list navigation', 'dexpress' ),
            'filter_items_list'     => esc_html__( 'Filter items list', 'dexpress' ),
        );
        $team_args = array(
            'label'                 => esc_html__( 'Team', 'dexpress' ),
            'description'           => esc_html__( 'dexpress Team', 'dexpress' ),
            'labels'                => $dexpress_team_labels,
            'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions','page-attributes'),
            'hierarchical'          => true,
            'public'                => true,
            'show_ui'               => true,
            'show_in_menu'          => true,
            'menu_position'         => 5,
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'can_export'            => true,
            'has_archive'           => true,		
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'capability_type'       => 'page',
            'menu_icon'             => 'dashicons-migrate'
        );
        register_post_type( 'dexpress-team', $team_args );
        $dexpress_gallery_labels = array(
		'name'                  => _x( 'Gallery', 'Post Type General Name', 'dexpress' ),
		'singular_name'         => _x( 'Gallery', 'Post Type Singular Name', 'dexpress' ),
		'menu_name'             => esc_html__( 'Gallery', 'dexpress' ),
		'name_admin_bar'        => esc_html__( 'Gallery', 'dexpress' ),
		'archives'              => esc_html__( 'Gallery Archives', 'dexpress' ),
		'attributes'            => esc_html__( 'Gallery Attributes', 'dexpress' ),
		'parent_item_colon'     => esc_html__( 'Parent Item:', 'dexpress' ),
		'all_items'             => esc_html__( 'All Gallery', 'dexpress' ),
		'add_new_item'          => esc_html__( 'Add New Gallery', 'dexpress' ),
		'add_new'               => esc_html__( 'Add New Gallery', 'dexpress' ),
		'new_item'              => esc_html__( 'New Gallery', 'dexpress' ),
		'edit_item'             => esc_html__( 'Gallery Edit', 'dexpress' ),
		'update_item'           => esc_html__( 'Update Gallery', 'dexpress' ),
		'view_item'             => esc_html__( 'View Item', 'dexpress' ),
		'view_items'            => esc_html__( 'View Gallery item', 'dexpress' ),
		'search_items'          => esc_html__( 'Gallery Search', 'dexpress' ),
		'not_found'             => esc_html__( 'Not found', 'dexpress' ),
		'not_found_in_trash'    => esc_html__( 'Not found in Trash', 'dexpress' ),
		'featured_image'        => esc_html__( 'Featured Image', 'dexpress' ),
		'set_featured_image'    => esc_html__( 'Set featured image', 'dexpress' ),
		'remove_featured_image' => esc_html__( 'Remove featured image', 'dexpress' ),
		'use_featured_image'    => esc_html__( 'Use as featured image', 'dexpress' ),
		'insert_into_item'      => esc_html__( 'Insert into item', 'dexpress' ),
		'uploaded_to_this_item' => esc_html__( 'Uploaded to Gallery item', 'dexpress' ),
		'items_list'            => esc_html__( 'Gallery item list', 'dexpress' ),
		'items_list_navigation' => esc_html__( 'Gallery list navigation', 'dexpress' ),
		'filter_items_list'     => esc_html__( 'Filter items list', 'dexpress' ),
	);
	$gallery_args = array(
		'label'                 => esc_html__( 'Gallery', 'dexpress' ),
		'description'           => esc_html__( 'dexpress Gallery', 'dexpress' ),
		'labels'                => $dexpress_gallery_labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions','view_mode_post_types','video' ),
		//'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-migrate'
	);
	register_post_type( 'dexpress-gallery', $gallery_args );

}
add_action( 'init', 'dexpress_post_type', 0 );

if ( ! function_exists( 'category_custom_taxonomy' ) ) {
    // Register Custom Taxonomy
function category_custom_taxonomy() {
	$labels = array(
		'name'                       => _x( 'Work:', 'Taxonomy General Name', 'dexpress' ),
		'singular_name'              => _x( 'Work Category', 'Taxonomy Singular Name', 'dexpress' ),
		'menu_name'                  => esc_html__( 'Category', 'dexpress' ),
		'all_items'                  => esc_html__( 'All Categories', 'dexpress' ),
		'parent_item'                => esc_html__( 'Parent Category', 'dexpress' ),
		'parent_item_colon'          => esc_html__( 'Parent Category:', 'dexpress' ),
		'new_item_name'              => esc_html__( 'New Category Name', 'dexpress' ),
		'add_new_item'               => esc_html__( 'Add New Category', 'dexpress' ),
		'edit_item'                  => esc_html__( 'Edit Category', 'dexpress' ),
		'update_item'                => esc_html__( 'Update Category', 'dexpress' ),
		'view_item'                  => esc_html__( 'View Category', 'dexpress' ),
		'separate_items_with_commas' => esc_html__( 'Separate Categories with commas', 'dexpress' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Categories', 'dexpress' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used', 'dexpress' ),
		'popular_items'              => esc_html__( 'Popular Categories', 'dexpress' ),
		'search_items'               => esc_html__( 'Search Categories', 'dexpress' ),
		'not_found'                  => esc_html__( 'Not Found', 'dexpress' ),
		'no_terms'                   => esc_html__( 'No Categories', 'dexpress' ),
		'items_list'                 => esc_html__( 'Categories list', 'dexpress' ),
		'items_list_navigation'      => esc_html__( 'Categories list navigation', 'dexpress' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'work_category', array( 'dexpress-work' ), $args );
    
    $labels = array(
		'name'                       => _x( 'Service Categories', 'Taxonomy General Name', 'dexpress' ),
		'singular_name'              => _x( 'Service Category', 'Taxonomy Singular Name', 'dexpress' ),
		'menu_name'                  => esc_html__( 'Category', 'dexpress' ),
		'all_items'                  => esc_html__( 'All Categories', 'dexpress' ),
		'parent_item'                => esc_html__( 'Parent Category', 'dexpress' ),
		'parent_item_colon'          => esc_html__( 'Parent Category:', 'dexpress' ),
		'new_item_name'              => esc_html__( 'New Category Name', 'dexpress' ),
		'add_new_item'               => esc_html__( 'Add New Category', 'dexpress' ),
		'edit_item'                  => esc_html__( 'Edit Category', 'dexpress' ),
		'update_item'                => esc_html__( 'Update Category', 'dexpress' ),
		'view_item'                  => esc_html__( 'View Category', 'dexpress' ),
		'separate_items_with_commas' => esc_html__( 'Separate Categories with commas', 'dexpress' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Categories', 'dexpress' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used', 'dexpress' ),
		'popular_items'              => esc_html__( 'Popular Categories', 'dexpress' ),
		'search_items'               => esc_html__( 'Search Categories', 'dexpress' ),
		'not_found'                  => esc_html__( 'Not Found', 'dexpress' ),
		'no_terms'                   => esc_html__( 'No Categories', 'dexpress' ),
		'items_list'                 => esc_html__( 'Categories list', 'dexpress' ),
		'items_list_navigation'      => esc_html__( 'Categories list navigation', 'dexpress' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'service_category', array( 'dexpress-service' ), $args );
    $labels = array(
		'name'                       => _x( 'Testmonial Categories', 'Taxonomy General Name', 'dexpress' ),
		'singular_name'              => _x( 'Testmonial Category', 'Taxonomy Singular Name', 'dexpress' ),
		'menu_name'                  => esc_html__( 'Category', 'dexpress' ),
		'all_items'                  => esc_html__( 'All Categories', 'dexpress' ),
		'parent_item'                => esc_html__( 'Parent Category', 'dexpress' ),
		'parent_item_colon'          => esc_html__( 'Parent Category:', 'dexpress' ),
		'new_item_name'              => esc_html__( 'New Category Name', 'dexpress' ),
		'add_new_item'               => esc_html__( 'Add New Category', 'dexpress' ),
		'edit_item'                  => esc_html__( 'Edit Category', 'dexpress' ),
		'update_item'                => esc_html__( 'Update Category', 'dexpress' ),
		'view_item'                  => esc_html__( 'View Category', 'dexpress' ),
		'separate_items_with_commas' => esc_html__( 'Separate Categories with commas', 'dexpress' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Categories', 'dexpress' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used', 'dexpress' ),
		'popular_items'              => esc_html__( 'Popular Categories', 'dexpress' ),
		'search_items'               => esc_html__( 'Search Categories', 'dexpress' ),
		'not_found'                  => esc_html__( 'Not Found', 'dexpress' ),
		'no_terms'                   => esc_html__( 'No Categories', 'dexpress' ),
		'items_list'                 => esc_html__( 'Categories list', 'dexpress' ),
		'items_list_navigation'      => esc_html__( 'Categories list navigation', 'dexpress' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'testmonial_category', array( 'dexpress_testimonial' ), $args );
    $labels = array(
		'name'                       => _x( 'Team Categories', 'Taxonomy General Name', 'dexpress' ),
		'singular_name'              => _x( 'Team Category', 'Taxonomy Singular Name', 'dexpress' ),
		'menu_name'                  => esc_html__( 'Category', 'dexpress' ),
		'all_items'                  => esc_html__( 'All Categories', 'dexpress' ),
		'parent_item'                => esc_html__( 'Parent Category', 'dexpress' ),
		'parent_item_colon'          => esc_html__( 'Parent Category:', 'dexpress' ),
		'new_item_name'              => esc_html__( 'New Category Name', 'dexpress' ),
		'add_new_item'               => esc_html__( 'Add New Category', 'dexpress' ),
		'edit_item'                  => esc_html__( 'Edit Category', 'dexpress' ),
		'update_item'                => esc_html__( 'Update Category', 'dexpress' ),
		'view_item'                  => esc_html__( 'View Category', 'dexpress' ),
		'separate_items_with_commas' => esc_html__( 'Separate Categories with commas', 'dexpress' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Categories', 'dexpress' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used', 'dexpress' ),
		'popular_items'              => esc_html__( 'Popular Categories', 'dexpress' ),
		'search_items'               => esc_html__( 'Search Categories', 'dexpress' ),
		'not_found'                  => esc_html__( 'Not Found', 'dexpress' ),
		'no_terms'                   => esc_html__( 'No Categories', 'dexpress' ),
		'items_list'                 => esc_html__( 'Categories list', 'dexpress' ),
		'items_list_navigation'      => esc_html__( 'Categories list navigation', 'dexpress' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'dexpress-teamcat', array( 'dexpress-team' ), $args );
}
add_action( 'init', 'category_custom_taxonomy', 0 );

}
